CONFIG_INPUT=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_HID=y
CONFIG_USB_DEVICE_VID=0x2FE2
CONFIG_USB_DEVICE_PID=0x0004
CONFIG_USB_DEVICE_MANUFACTURER="Zephyr"
CONFIG_USB_DEVICE_PRODUCT="2x2 Keypad HID"
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_I2S=y
CONFIG_NRFX_USBREG=y
CONFIG_USB_HID_BOOT_PROTOCOL=y
CONFIG_USB_CDC_ACM=y
# CONFIG_LOG=y

CONFIG_NCS_SAMPLES_DEFAULTS=y

